### ISSUE TITLE
Installing breaks Discord

### ISSUE THREAD

**Issue by Fabian42** [GooseMod/OpenAsar#171]
After installing `openasar-git` (version `r826.84b3df4-1`) from AUR, it breaks Discord 0.39 startup:

```
[OpenAsar > Init] OpenAsar nightly-84b3df4
[OpenAsar > Settings] /home/fabian/.config/discord/settings.json {
  IS_MAXIMIZED: true,
  IS_MINIMIZED: false,
  WINDOW_BOUNDS: { x: 0, y: 52, width: 960, height: 1028 },
  openasar: { setup: true, noTrack: false, quickstart: true },
  trayBalloonShown: true
}
[OpenAsar > BuildInfo] { releaseChannel: 'stable', version: '0.0.39' }
[OpenAsar > Modules] Checking
Error: Cannot find module 'discord_desktop_core'
Require stack:
- /opt/discord/resources/app.asar/bootstrap.js
- /opt/discord/resources/app.asar/index.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:963:15)
    at n._resolveFilename (node:electron/js2c/browser_init:2:109751)
    at Module._load (node:internal/modules/cjs/loader:811:27)
    at f._load (node:electron/js2c/asar_bundle:2:13377)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at startCore (/opt/discord/resources/app.asar/bootstrap.js:1:1517)
    at EventEmitter.<anonymous> (/opt/discord/resources/app.asar/bootstrap.js:1:2630)
    at Object.onceWrapper (node:events:627:28)
    at EventEmitter.emit (node:events:513:28) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/discord/resources/app.asar/bootstrap.js',
    '/opt/discord/resources/app.asar/index.js',
    undefined
  ]
} uncaughtException
```

I completely uninstalled both and then installed both again to check. Discord gets to its usual faulty update checker and refuses to start due to stupidity before installing OpenASAR (so everything "normal", for Discord) and crashes after installing OpenASAR.

**Comment by CanadaHonk** [comment]
Change quickstart to false inside of `~/.config/discord/settings.json`.

**Comment by Fabian42** [comment]
Thanks, that worked! I have still not figured out how to installed Discord updates and keep everything working…
