### ISSUE TITLE
TypeError: desktopCore.startup is not a function

### ISSUE THREAD

**Issue by c4p-n1ck** [GooseMod/OpenAsar#75]
```sh
$ sudo cp ~/Downloads/app.asar /opt/discord/resources/app.asar  # Downloaded from: https://openasar.dev/#
$ discord
```
```js
[OpenAsar > Init] OpenAsar nightly-6f7505f
[OpenAsar > Settings] /home/nick/.config/discord/settings.json {
  IS_MAXIMIZED: false,
  IS_MINIMIZED: false,
  WINDOW_BOUNDS: { x: 965, y: 38, width: 945, height: 1004 },
  BACKGROUND_COLOR: '#202225',
  openasar: { setup: true, quickstart: true, multiInstance: true },
  trayBalloonShown: true
}
[OpenAsar > BuildInfo] { releaseChannel: 'stable', version: '0.0.18' }
[OpenAsar > Modules] Checking
libva error: /usr/lib/dri/i965_drv_video.so init failed
TypeError: desktopCore.startup is not a function
    at startCore (/opt/discord/resources/app.asar/bootstrap.js:1:1428)
    at EventEmitter.<anonymous> (/opt/discord/resources/app.asar/bootstrap.js:1:2328)
    at Object.onceWrapper (events.js:421:28)
    at EventEmitter.emit (events.js:315:20)
    at launchMain (/opt/discord/resources/app.asar/splash/index.js:1:830)
    at Timeout._onTimeout (/opt/discord/resources/app.asar/splash/index.js:1:370)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) uncaughtException
```

This used to work fine before, not sure what the issue really is.

**Comment by c4p-n1ck** [comment]
Issue seemed to persist in Windows too.
```
[OpenAsar > Init] OpenAsar nightly-6f7505f
[OpenAsar > Settings] C:\Users\acer\AppData\Roaming\discord\settings.json {
  IS_MAXIMIZED: false,
  IS_MINIMIZED: false,
  WINDOW_BOUNDS: { x: 0, y: 12, width: 1258, height: 660 },
  BACKGROUND_COLOR: '#202225'
}
[OpenAsar > BuildInfo] { newUpdater: true, releaseChannel: 'stable', version: '1.0.9005' }
[OpenAsar > Splash] TypeError: desktopCore.startup is not a function
    at startCore (C:\Users\acer\AppData\Local\Discord\app-1.0.9005\resources\app.asar\bootstrap.js:1:1428)
    at EventEmitter.<anonymous> (C:\Users\acer\AppData\Local\Discord\app-1.0.9005\resources\app.asar\bootstrap.js:1:2328)
    at Object.onceWrapper (events.js:421:28)
    at EventEmitter.emit (events.js:315:20)
    at launchMain (C:\Users\acer\AppData\Local\Discord\app-1.0.9005\resources\app.asar\splash\index.js:1:830)
    at initNew (C:\Users\acer\AppData\Local\Discord\app-1.0.9005\resources\app.asar\splash\index.js:1:2891)
```

**Comment by CanadaHonk** [comment]
Have you tried disabling quickstart?

**Comment by CanadaHonk** [comment]
Please use [our Discord](https://discord.com/invite/neMncS2) for support as it provides easier communication/sharing. Thanks!
